### ISSUE TITLE
Migration rClr=>rSharp

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Suite#143]
* [x] Windows version
  * [ ] Memory Leak profiling
* [x] Test ospsuite-R on Windows
* [x] Linux version
* [x] Test ospsuite-R on Linux
* [x] Switch ospsuite-R from rClr to rSharp
* [x] Switch RE from rClr to rSharp
* [ ]

**Comment by PavelBal** [comment]
@Yuri05 @msevestre 
- A working version of `rSharp` can be found in the `develop` branch here https://github.com/Open-Systems-Pharmacology/rSharp
- [User guide](http://www.open-systems-pharmacology.org/rSharp/articles/user-guide.html) describing the syntax.
- ospsuite-r migrated to `rSharp` is on this branch https://github.com/Open-Systems-Pharmacology/OSPSuite-R/tree/r-sharp-r6
- Regarding performance - I am not motivated to write proper benchmarks. I compare the execution time for running all ospsuite-r tests (except for those that require PK-Sim).

`rClr` version: 282 seconds (median of 10 runs)
`rSharp` version: 242 seconds (median of 10 runs)

Hard to tell where this "improvement" comes from, but at least for our cases, the performance of `rSharp` is comparable to that of `rClr`.

**Comment by rwmcintosh** [comment]
Since we have this new Dependency Resolver project https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2909

I think we can limit the assemblies and projects that are critical for rSharp to the packages that are deployed there.

In other words, if we can update OSPSuite.Utility solution, OSPSuite.Serializer solution and only those packages that are necessary for OSPSuite-R

- PKSimDependencyResolver from PK-Sim solution
- OSPSuite.R from OSPSuite.Core solution

That would be enough. I bet most of those already compile with .NET standard 2.0 or later. There might be a few more to find, but in general, we would not need
- DataBinding
- DataBinding.DevExpress
- any UI project from OSPSuite.Core or PK-Sim

**Comment by msevestre** [comment]
@rwmcintosh I don't understand why you are mentioning DataBinding and DevExpress?

**Comment by msevestre** [comment]
>if we can update OSPSuite.Utility solution, OSPSuite.Serializer solution and 

Update to what? I don't get it

**Comment by rwmcintosh** [comment]
> @rwmcintosh I don't understand why you are mentioning DataBinding and DevExpress?

I have modified this issue since then. Ben and I were talking about steps today and listed in here were upgrades to DataBinding and DevExpress.DataBinding.

Formerly, we were thinking that we would upgrade all of PK-Sim to .NET 8, but now, with the dependency resolver project, we can update only that project and all its dependencies (DataBinding and DevExpress.DataBinding are not dependencies). So I took those out of the task list.

Also, we won't need to update the UI components, for now... rSharp will work with PK-Sim without updating UI projects.

**Comment by msevestre** [comment]
yeah but we need to upgrade so that we can use the latest framework. We are stuck in the past right now. I believe this is urgent

**Comment by rwmcintosh** [comment]
Could be, but to get rSharp in service we don't need the UI upgraded. 

I think we can also release an rSharp with .NET 8 along with V12 if we don't upgrade the UI projects. Upgrading the UI projects adds a lot of testing that we could do after V12.

**Comment by msevestre** [comment]
Yes I didn’t say for v12. I am just saying that we need to upgrade

**Comment by rwmcintosh** [comment]
yeah, so for this, we only do what's required for rSharp, release that, then upgrade UI and binding in separate PR's, probably as the first merge in V13

**Comment by Yuri05** [comment]
>I think we can also release an rSharp with .NET 8 along with V12 if we don't upgrade the UI projects.

This would be the preferable scenario.

**Comment by rwmcintosh** [comment]
We are fully migrated to rSharp
